### ISSUE TITLE
Clarify  bootstrap_range and ip_range

### ISSUE THREAD

**Issue by danehans** [giantswarm/mayu#60]
```mayu/docs/configuration.md``` states the following:

> Here we have three less obvious settings: the `bootstrap_range` is used by the
DHCP server during the bootstrap procedure and the nodes only use it during the
installation. The `ip_range` is a range of addresses that will be statically
assigned to the cluster nodes. The `network_model` specifies which network
template snippet will be used.

```mayu/config.yaml.dist``` shows the following example:
```
  bootstrap_range:
    start: 10.0.3.10
    end: 10.0.3.30
  ip_range:
    start: 10.0.3.31
    end: 10.0.3.70
```

Can you help me better understand why a separate ip range is needed for bootstrapping? Dedicating a large range of IP's within a subnet just for a temporary bootstrap process is suboptimal. This basically makes half of my subnet unusable.
