### ISSUE TITLE
mayu not delivering cloud-init

### ISSUE THREAD

**Issue by danehans** [giantswarm/mayu#61]
mayu is pxe booting coreos to my servers. However, I am unable to ssh to the servers. Here are some details:
```
[localadmin@gem-master01 mayu]$ cat /etc/mayu/config.yaml 
network:
  pxe: true
  interface: enp15s0
  bind_addr: 10.30.118.133
  bootstrap_range:
    start: 10.30.118.140
    end: 10.30.118.145
  ip_range:
    start: 10.30.118.146
    end: 10.30.118.150
  dns: [172.29.74.154, 8.8.8.8, 8.8.4.4]
  router: 10.30.118.129
  network_model: singlenic

profiles:
  - name: core
    quantity: 3
    tags:
      - "role-core=true"
    coreos_version: "835.13.0"
  - name: default
    disable_engine: true
    coreos_version: "835.13.0"
    tags:
      - "role-worker=true"
      - "stack-compute=true"

templates_env:
  ssh_authorized_keys:
    - "ssh-rsa <my_key_1>"
    - "ssh-rsa <my_key_2>"
  mayu_http_endpoint: "http://10.30.118.133:4080"
```

```/etc/mayu``` is being mounted to the container:
```
 systemctl cat mayu.service
# /etc/systemd/system/mayu.service
[Unit]
Description=Mayu
After=docker.service
Requires=docker.service

[Service]
Restart=always
TimeoutStartSec=0
ExecStart=/usr/bin/docker run --rm --cap-add=NET_ADMIN --net=host \
        -v /var/lib/mayu:/var/lib/mayu \
        -v /var/lib/mayu/images:/usr/lib/mayu/images \
        -v /etc/mayu:/etc/mayu \
        -v /etc/resolv.conf:/etc/resolv.conf \
        -v /etc/hosts:/etc/hosts \
        --name mayu \
        giantswarm/mayu \
        -v=12 --no-tls

[Install]
WantedBy=multi-user.target
```

When I try to SSH to a coreos server provisioned by mayu, I get the following:
```
$ ssh core@10.30.118.144
The authenticity of host '10.30.118.144 (10.30.118.144)' can't be established.
RSA key fingerprint is 32:a6:11:6f:ac:35:95:52:40:d1:7b:da:ce:04:bc:71.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.30.118.144' (RSA) to the list of known hosts.
core@10.30.118.144's password: 
```
